# -*- coding: utf-8 -*-
# Manifeste des images des fiches élève : concept -> requête de recherche
# Wikimedia Commons (ou nom de fichier Commons exact préfixé par "File:").
# Utilisé par scripts/chercher-images.py pour télécharger et créditer.

MANIFEST = {
    # ——— P1 · La ville ———
    "bus":            "London bus clipart drawing",
    "velo":           "bicycle clipart svg",
    "pigeon":         "pigeon bird photo white background",
    "fourmi":         "ant clipart svg",
    "escargot":       "File:Grapevinesnail 01.jpg",
    "coccinelle":     "ladybird beetle photo white background",
    "magasin":        "shop store building clipart",
    "feu-tricolore":  "traffic light clipart svg",
    "maison":         "house clipart svg simple",
    "moineau":        "House sparrow photo",
    "helicoptere":    "helicopter clipart svg",
    "immeuble":       "apartment building clipart",
    "ecole":          "school building clipart",
    "hopital":        "hospital building clipart",
    "baleine":        "whale clipart svg",
    "personne":       "person standing pictogram",
    "casque-velo":    "bicycle helmet clipart",
    "nid":            "bird nest eggs photo",
    "piscine":        "swimming pictogram",
    "cinema":         "cinema film clapperboard clipart",

    # ——— P2 · La forêt ———
    "hibou":          "owl clipart svg",
    "loup":           "wolf clipart svg",
    "caillou":        "pebble stone photo white background",
    "renard":         "fox clipart svg",
    "sapin":          "fir tree clipart svg",
    "genou":          "knee human pictogram",
    "marron":         "File:Chestnuts (2).jpg",
    "herisson":       "hedgehog photo white background",
    "champignon":     "mushroom clipart svg",
    "ecureuil":       "red squirrel photo",
    "noisette":       "hazelnut photo white background",
    "gland":          "acorn photo white background",
    "feuille-morte":  "autumn leaf photo white background",
    "pomme":          "red apple photo white background",
    "terrier":        "burrow hole ground photo",
    "fourmiliere":    "anthill photo",
    "arbre-creux":    "tree hollow photo",
    "cerf":           "red deer stag photo",
    "sanglier":       "wild boar photo",
    "canard":         "mallard duck photo",
    "ourson":         "teddy bear photo white background",
    "ver-de-terre":   "earthworm photo",
    "ballon":         "balloon red clipart",
    "buche":          "wood log photo white background",

    # ——— P3 · La montagne ———
    "flocon":         "snowflake clipart svg blue",
    "luge":           "sled sledge clipart",
    "chamois":        "chamois animal photo",
    "moto":           "motorcycle clipart svg",
    "chocolat-chaud": "hot chocolate mug clipart",
    "lama":           "llama photo white background",
    "aigle":          "golden eagle photo",
    "marmotte":       "alpine marmot photo",
    "bouquetin":      "alpine ibex photo",
    "igloo":          "igloo clipart svg",
    "ski":            "skiing pictogram",
    "moufle":         "mitten clipart",
    "montagne":       "mountain peak clipart svg",
    "pluie":          "rain cloud clipart svg",
    "glacon":         "ice cube photo white background",
    "bonhomme-neige": "snowman clipart svg",
    "robinet":        "water tap faucet clipart",
    "glacier":        "glacier photo mountain",
    "goutte":         "water drop clipart svg",
    "soleil":         "sun clipart svg",
    "echarpe":        "scarf clipart",
    "manteau":        "winter coat clipart",
    "chapeau-soleil": "sun hat clipart",
    "tongs":          "flip flops clipart",
    "maillot":        "swimsuit clipart",
    "oies-migration": "geese flying migration photo",
    "mouton":         "sheep photo white background",
    "avion":          "airplane clipart svg",

    # ——— P4 · La campagne ———
    "salade":         "lettuce photo white background",
    "chenille":       "caterpillar photo",
    "cheval":         "horse photo white background",
    "poussin":        "chick yellow photo white background",
    "vache":          "cow photo white background",
    "souris":         "mouse animal photo white background",
    "oeuf":           "chicken egg photo white background",
    "poule":          "hen chicken photo white background",
    "fleur":          "flower daisy clipart svg",
    "tournesol":      "sunflower photo white background",
    "cerise":         "cherries photo white background",
    "fraise":         "strawberry photo white background",
    "radis":          "radish photo white background",
    "tomate":         "tomato photo white background",
    "carotte":        "carrot photo white background",
    "lapin":          "rabbit photo white background",
    "pot-de-fleur":   "flower pot clipart",
    "graine":         "seeds photo white background",
    "papillon":       "butterfly photo white background",
    "chrysalide":     "chrysalis pupa photo",
    "sucre":          "sugar cubes photo white background",
    "sel":            "salt shaker clipart",
    "sable":          "sand pile photo",
    "citrouille":     "pumpkin photo white background",
    "patate":         "potato photo white background",
    "haricot":        "beans photo white background",
    "chat":           "cat photo white background",
    "voiture":        "car clipart svg side",
    "serpent":        "snake clipart svg",
    "vent":           "wind blowing clipart",
    "television":     "television clipart svg",
    "chocolat":       "chocolate bar photo white background",

    # ——— P5 · La mer ———
    "phare":          "lighthouse clipart svg",
    "vague":          "wave sea clipart svg",
    "dauphin":        "dolphin photo",
    "filet-peche":    "fishing net photo",
    "voilier":        "sailboat clipart svg",
    "fusee":          "rocket clipart svg",
    "crabe":          "crab photo white background",
    "mouette":        "seagull photo",
    "seau-plage":     "beach bucket clipart",
    "pelle-plage":    "beach shovel spade clipart",
    "coquillage":     "seashell photo white background",
    "etoile-de-mer":  "starfish photo white background",
    "poisson":        "fish clipart svg",
    "bois":           "wood plank photo white background",
    "fer":            "iron nail photo white background",
    "bouchon-liege":  "cork stopper photo white background",
    "calamar":        "squid photo",
    "collier-perles": "pearl necklace photo white background",
    "ile":            "island palm clipart",
    "riz":            "rice bowl photo white background",
}

# Compléments (2e passe)
MANIFEST.update({
    "plage":        "sandy beach photo sea",
    "pousse":       "seedling sprout soil photo",
    "plante-jeune": "young plant leaves pot photo",
    "eclosion":     "chick hatching egg photo",
})
