# -*- coding: utf-8 -*-
# Manifeste des images des fiches élève : concept -> requête de recherche
# Wikimedia Commons (ou nom de fichier Commons exact préfixé par "File:").
# Utilisé par scripts/chercher-images.py pour télécharger et créditer.

MANIFEST = {
    # ——— P1 · La ville ———
    "bus":            "London bus clipart drawing",
    "velo":           "bicycle clipart svg",
    "pigeon":         "pigeon bird photo white background",
    "fourmi":         "ant clipart svg",
    "escargot":       "File:Grapevinesnail 01.jpg",
    "coccinelle":     "ladybird beetle photo white background",
    "magasin":        "shop store building clipart",
    "feu-tricolore":  "traffic light clipart svg",
    "maison":         "house clipart svg simple",
    "moineau":        "House sparrow photo",
    "helicoptere":    "helicopter clipart svg",
    "immeuble":       "apartment building clipart",
    "ecole":          "school building clipart",
    "hopital":        "hospital building clipart",
    "baleine":        "whale clipart svg",
    "personne":       "person standing pictogram",
    "casque-velo":    "bicycle helmet clipart",
    "nid":            "bird nest eggs photo",
    "piscine":        "swimming pictogram",
    "cinema":         "cinema film clapperboard clipart",

    # ——— P2 · La forêt ———
    "hibou":          "owl clipart svg",
    "loup":           "wolf clipart svg",
    "caillou":        "pebble stone photo white background",
    "renard":         "fox clipart svg",
    "sapin":          "fir tree clipart svg",
    "genou":          "knee human pictogram",
    "marron":         "File:Chestnuts (2).jpg",
    "herisson":       "hedgehog photo white background",
    "champignon":     "mushroom clipart svg",
    "ecureuil":       "red squirrel photo",
    "noisette":       "hazelnut photo white background",
    "gland":          "acorn photo white background",
    "feuille-morte":  "autumn leaf photo white background",
    "pomme":          "red apple photo white background",
    "terrier":        "burrow hole ground photo",
    "fourmiliere":    "anthill photo",
    "arbre-creux":    "tree hollow photo",
    "cerf":           "red deer stag photo",
    "sanglier":       "wild boar photo",
    "canard":         "mallard duck photo",
    "ourson":         "teddy bear photo white background",
    "ver-de-terre":   "earthworm photo",
    "ballon":         "balloon red clipart",
    "buche":          "wood log photo white background",

    # ——— P3 · La montagne ———
    "flocon":         "snowflake clipart svg blue",
    "luge":           "sled sledge clipart",
    "chamois":        "chamois animal photo",
    "moto":           "motorcycle clipart svg",
    "chocolat-chaud": "hot chocolate mug clipart",
    "lama":           "llama photo white background",
    "aigle":          "golden eagle photo",
    "marmotte":       "alpine marmot photo",
    "bouquetin":      "alpine ibex photo",
    "igloo":          "igloo clipart svg",
    "ski":            "skiing pictogram",
    "moufle":         "mitten clipart",
    "montagne":       "mountain peak clipart svg",
    "pluie":          "rain cloud clipart svg",
    "glacon":         "ice cube photo white background",
    "bonhomme-neige": "snowman clipart svg",
    "robinet":        "water tap faucet clipart",
    "glacier":        "glacier photo mountain",
    "goutte":         "water drop clipart svg",
    "soleil":         "sun clipart svg",
    "echarpe":        "scarf clipart",
    "manteau":        "winter coat clipart",
    "chapeau-soleil": "sun hat clipart",
    "tongs":          "flip flops clipart",
    "maillot":        "swimsuit clipart",
    "oies-migration": "geese flying migration photo",
    "mouton":         "sheep photo white background",
    "avion":          "airplane clipart svg",

    # ——— P4 · La campagne ———
    "salade":         "lettuce photo white background",
    "chenille":       "caterpillar photo",
    "cheval":         "horse photo white background",
    "poussin":        "chick yellow photo white background",
    "vache":          "cow photo white background",
    "souris":         "mouse animal photo white background",
    "oeuf":           "chicken egg photo white background",
    "poule":          "hen chicken photo white background",
    "fleur":          "flower daisy clipart svg",
    "tournesol":      "sunflower photo white background",
    "cerise":         "cherries photo white background",
    "fraise":         "strawberry photo white background",
    "radis":          "radish photo white background",
    "tomate":         "tomato photo white background",
    "carotte":        "carrot photo white background",
    "lapin":          "rabbit photo white background",
    "pot-de-fleur":   "flower pot clipart",
    "graine":         "seeds photo white background",
    "papillon":       "butterfly photo white background",
    "chrysalide":     "chrysalis pupa photo",
    "sucre":          "sugar cubes photo white background",
    "sel":            "salt shaker clipart",
    "sable":          "sand pile photo",
    "citrouille":     "pumpkin photo white background",
    "patate":         "potato photo white background",
    "haricot":        "beans photo white background",
    "chat":           "cat photo white background",
    "voiture":        "car clipart svg side",
    "serpent":        "snake clipart svg",
    "vent":           "wind blowing clipart",
    "television":     "television clipart svg",
    "chocolat":       "chocolate bar photo white background",

    # ——— P5 · La mer ———
    "phare":          "lighthouse clipart svg",
    "vague":          "wave sea clipart svg",
    "dauphin":        "dolphin photo",
    "filet-peche":    "fishing net photo",
    "voilier":        "sailboat clipart svg",
    "fusee":          "rocket clipart svg",
    "crabe":          "crab photo white background",
    "mouette":        "seagull photo",
    "seau-plage":     "beach bucket clipart",
    "pelle-plage":    "beach shovel spade clipart",
    "coquillage":     "seashell photo white background",
    "etoile-de-mer":  "starfish photo white background",
    "poisson":        "fish clipart svg",
    "bois":           "wood plank photo white background",
    "fer":            "iron nail photo white background",
    "bouchon-liege":  "cork stopper photo white background",
    "calamar":        "squid photo",
    "collier-perles": "pearl necklace photo white background",
    "ile":            "island palm clipart",
    "riz":            "rice bowl photo white background",
}

# Compléments (2e passe)
MANIFEST.update({
    "plage":        "sandy beach photo sea",
    "pousse":       "seedling sprout soil photo",
    "plante-jeune": "young plant leaves pot photo",
    "eclosion":     "chick hatching egg photo",
})

# 3e passe : requêtes photo (le mot-clé « clipart » échoue) + corrections
MANIFEST.update({
    "bus":            "London Routemaster bus photo",
    "coccinelle":     "Coccinella septempunctata photo leaf",
    "magasin":        "bakery shop front photo",
    "hopital":        "hospital building photo",
    "casque-velo":    "bicycle helmet photo",
    "sapin":          "Picea abies young tree",
    "genou":          "human knee photo",
    "marron":         "sweet chestnuts photo",
    "flocon":         "snowflake Bentley photo",
    "chocolat-chaud": "hot chocolate cup photo",
    "igloo":          "igloo snow photo",
    "moufle":         "wool mittens photo",
    "montagne":       "Matterhorn photo",
    "bonhomme-neige": "snowman photo",
    "maillot":        "swimming trunks photo",
    "fleur":          "Leucanthemum vulgare flower",
    "sel":            "salt shaker photo",
    "pelle-plage":    "beach toys bucket spade photo",
    "fer":            "metal nails photo",
    "bouchon-liege":  "wine cork photo",
    "navet":          "turnip photo white background",
    # corrections d'images fausses détectées
    "noisette":       "Corylus avellana hazelnuts photo",
    "gland":          "Quercus robur acorns photo",
    "buche":          "firewood logs photo",
})
MANIFEST.update({"ile": "small tropical island palm trees photo sea"})

# 4e passe : corrections après vérification visuelle des planches-contact
MANIFEST.update({
    "avion":         "Airbus A320 flight photo sky",
    "bois":          "wooden board plank photo",
    "bonhomme-neige":"snowman photo winter carrot nose",
    "caillou":       "smooth pebbles stones photo",
    "calamar":       "Sepioteuthis squid swimming photo",
    "carotte":       "carrots bunch photo market",
    "casque-velo":   "bicycle helmet blue photo",
    "chamois":       "Rupicapra rupicapra alps photo",
    "chapeau-soleil":"straw hat photo",
    "chat":          "tabby cat sitting photo",
    "chocolat":      "dark chocolate tablet squares photo",
    "chrysalide":    "monarch chrysalis green photo",
    "cinema":        "film clapperboard photo",
    "citrouille":    "orange pumpkin photo field",
    "coccinelle":    "seven-spot ladybird macro photo",
    "coquillage":    "Pecten maximus scallop shell photo",
    "crabe":         "Cancer pagurus crab photo",
    "echarpe":       "knitted wool scarf photo",
    "filet-peche":   "fishing net mesh close-up photo",
    "flocon":        "Bentley snowflake single crystal",
    "fourmiliere":   "wood ant nest forest photo",
    "fusee":         "Soyuz rocket launch photo",
    "glacon":        "ice cubes glass photo",
    "goutte":        "water droplet splash crown photo",
    "graine":        "pumpkin seeds photo",
    "haricot":       "green beans pods photo",
    "helicoptere":   "helicopter in flight photo",
    "hopital":       "hospital building entrance photo",
    "igloo":         "File:Igloo.jpg",
    "immeuble":      "apartment block facade photo",
    "lama":          "Lama glama animal photo",
    "lapin":         "European rabbit sitting grass photo",
    "loup":          "Canis lupus wolf portrait photo",
    "luge":          "wooden sledge snow photo",
    "maillot":       "swim trunks photo",
    "maison":        "cottage house garden photo",
    "manteau":       "winter parka jacket photo",
    "marron":        "Castanea sativa fruits photo",
    "moineau":       "Passer domesticus male perched photo",
    "montagne":      "File:Matterhorn from Domhütte - 2.jpg",
    "mouton":        "domestic sheep wool grass photo",
    "nid":           "blackbird nest eggs photo",
    "noisette":      "hazelnuts kernels photo",
    "papillon":      "Vanessa atalanta butterfly photo",
    "pigeon":        "File:Rock dove - natures pics.jpg",
    "piscine":       "swimming pool lanes water photo",
    "plante-jeune":  "tomato seedling pot photo",
    "poisson":       "Carassius auratus goldfish photo",
    "pousse":        "bean seedling sprouting soil photo",
    "poussin":       "yellow chick Gallus photo",
    "radis":         "red radishes bunch photo",
    "renard":        "Vulpes vulpes fox snow photo",
    "riz":           "uncooked white rice grains photo",
    "sable":         "sand ripples beach texture photo",
    "salade":        "iceberg lettuce head photo",
    "sapin":         "Nordmann fir tree photo",
    "serpent":       "grass snake Natrix photo",
    "ski":           "alpine skiing downhill photo",
    "soleil":        "bright sun sky clouds photo",
    "tomate":        "File:Tomato je.jpg",
    "vache":         "File:Cow female black white.jpg",
    "vague":         "ocean wave breaking photo",
    "velo":          "File:Left side of Flying Pigeon.jpg",
    "vent":          "windsock photo",
    "ver-de-terre":  "earthworm Lumbricus soil photo",
    "voilier":       "sloop sailboat sailing sea photo",
    "voiture":       "hatchback car side view photo",
})

# 5e passe : remplacer les cliparts « façon émoji » par des photos
MANIFEST.update({
    "baleine":       "humpback whale breaching photo",
    "champignon":    "Amanita muscaria forest photo",
    "moto":          "motorcycle side view photo",
    "hibou":         "Bubo bubo owl photo",
    "ecole":         "school building facade photo france",
    "phare":         "lighthouse sea photo",
    "television":    "television set photo",
    "robinet":       "water tap photo dripping",
    "pluie":         "rain drops puddle photo",
    "fourmi":        "Formica rufa ant macro photo",
    "feu-tricolore": "traffic lights street photo",
    "ballon":        "red balloon sky photo",
})
MANIFEST.update({
    "flocon":      "snow crystal Wilson Bentley",
    "poussin":     "Gallus gallus domesticus chick photo",
    "chocolat":    "chocolate tablet pieces photo",
    "filet-peche": "fishing nets harbour photo",
    "calamar":     "Loligo vulgaris photo",
})
MANIFEST.update({"chocolat": "File:Chocolate02.jpg", "flocon": "File:Bentley Snowflake11.jpg"})

# 6e passe : revue stricte v2 — sujet unique, net, adapté à des enfants
MANIFEST.update({
    "ballon":        "party balloon red photo",
    "bois":          "plank wood texture photo",
    "bonhomme-neige":"snowman closeup photo",
    "bouchon-liege": "wine cork single photo",
    "buche":         "cut log wood photo",
    "caillou":       "grey pebble single photo",
    "carotte":       "carrot isolated photo",
    "casque-velo":   "bike helmet photo isolated",
    "chapeau-soleil":"straw hat isolated photo",
    "cheval":        "horse standing profile pasture photo",
    "cinema":        "movie theater auditorium seats photo",
    "citrouille":    "pumpkin isolated photo",
    "echarpe":       "wool scarf isolated photo",
    "ecole":         "école primaire façade photo",
    "fer":           "nail iron isolated photo",
    "feu-tricolore": "traffic light signal sky photo",
    "flocon":        "snow crystal microscope single photo",
    "fourmi":        "ant side view macro photo",
    "haricot":       "green beans heap photo",
    "helicoptere":   "helicopter hovering blue sky photo",
    "lama":          "llama portrait photo",
    "lapin":         "Oryctolagus cuniculus close photo",
    "luge":          "toboggan sled snow photo",
    "tee-shirt":     "plain t-shirt photo",
    "maison":        "single family house front photo",
    "manteau":       "duffle coat photo",
    "marron":        "conkers horse chestnut photo",
    "moto":          "motorbike parked side photo",
    "noisette":      "hazelnuts in shell photo",
    "ourson":        "brown teddy bear photo",
    "phare":         "lighthouse white red coast photo",
    "pluie":         "raindrops on window photo",
    "poisson":       "goldfish swimming orange photo",
    "pot-de-fleur":  "terracotta flowerpot empty photo",
    "pousse":        "seedling cotyledon soil photo",
    "poussin":       "chick yellow standing photo",
    "radis":         "radishes red bunch market photo",
    "riz":           "rice grains white macro photo",
    "robinet":       "outdoor tap water photo",
    "salade":        "lettuce plant garden photo",
    "sapin":         "single fir tree snow photo",
    "ski":           "skier downhill action photo",
    "soleil":        "sun bright disk photo",
    "vague":         "wave crashing surf photo",
    "vent":          "windsock airport orange photo",
    "ver-de-terre":  "File:Regenwurm1.jpg",
    "voiture":       "city car parked red photo",
})
