# -*- coding: utf-8 -*-
"""Manifeste de l'imagier Montessori « faune et flore ».

Pour chaque période (milieu) : 9 espèces de faune et 9 espèces de flore.
La flore, ce n'est pas seulement les fleurs : on y trouve les arbres, les
arbustes, les fougères, les mousses, les graminées, les algues et les
plantes cultivées, choisis pour être caractéristiques du milieu et
observables lors des sorties.

Chaque entrée décrit :
  slug   — nom de fichier de l'image (sans extension) ;
  nom    — le mot écrit sur l'étiquette (script, minuscules) ;
  taxon  — le nom scientifique, qui sert à interroger iNaturalist.

Utilisé par scripts/chercher-images-imagier.py (photographies + crédits)
et par scripts/generer-imagier.py (génération des planches HTML).
"""

MILIEUX = [
    (1, "ville",    "🏙️", "La ville",    "Les animaux et les plantes de la ville, des parcs et des trottoirs."),
    (2, "foret",    "🌳", "La forêt",    "Les animaux et les plantes des bois et des sous-bois."),
    (3, "montagne", "⛰️", "La montagne", "Les animaux et les plantes de l’étage montagnard et alpin."),
    (4, "campagne", "🌾", "La campagne", "Les animaux de la ferme et des prés, les cultures et les fleurs des champs."),
    (5, "mer",      "🌊", "La mer",      "Les animaux du bord de mer, les plantes du littoral et les algues."),
]

IMAGIER = {
 1: {
  "faune": [
   ("pigeon-biset",          "le pigeon biset",          "Columba livia"),
   ("moineau-domestique",    "le moineau domestique",    "Passer domesticus"),
   ("merle-noir",            "le merle noir",            "Turdus merula"),
   ("mesange-charbonniere",  "la mésange charbonnière",  "Parus major"),
   ("martinet-noir",         "le martinet noir",         "Apus apus"),
   ("herisson-europe",       "le hérisson",              "Erinaceus europaeus"),
   ("ecureuil-roux",         "l’écureuil roux",          "Sciurus vulgaris"),
   ("coccinelle-7-points",   "la coccinelle",            "Coccinella septempunctata"),
   ("abeille-domestique",    "l’abeille",                "Apis mellifera"),
   ("pie-bavarde",               "la pie bavarde",              "Pica pica"),
   ("corneille-noire",           "la corneille noire",          "Corvus corone"),
   ("tourterelle-turque",        "la tourterelle turque",       "Streptopelia decaocto"),
   ("rougegorge",                "le rougegorge",               "Erithacus rubecula"),
   ("lezard-murailles",          "le lézard des murailles",     "Podarcis muralis"),
   ("escargot-petit-gris",       "l’escargot",                  "Cornu aspersum"),
   ("paon-du-jour",              "le paon-du-jour",             "Aglais io"),
   ("bourdon-terrestre",         "le bourdon",                  "Bombus terrestris"),
   ("epeire-diademe",            "l’épeire",                    "Araneus diadematus"),
  ],
  "flore": [
   ("platane",               "le platane",               "Platanus x hispanica"),
   ("marronnier",            "le marronnier",            "Aesculus hippocastanum"),
   ("tilleul",               "le tilleul",               "Tilia platyphyllos"),
   ("lierre",                "le lierre",                "Hedera helix"),
   ("mousse-trottoir",       "la mousse",                "Bryum argenteum"),
   ("paquerette",            "la pâquerette",            "Bellis perennis"),
   ("pissenlit",             "le pissenlit",             "Taraxacum officinale"),
   ("rose-tremiere",         "la rose trémière",         "Alcea rosea"),
   ("geranium-balcon",       "le géranium",              "Pelargonium zonale"),
   ("erable-sycomore",           "l’érable",                    "Acer pseudoplatanus"),
   ("robinier",                  "le robinier",                 "Robinia pseudoacacia"),
   ("lilas",                     "le lilas",                    "Syringa vulgaris"),
   ("buis",                      "le buis",                     "Buxus sempervirens"),
   ("vigne-vierge",              "la vigne vierge",             "Parthenocissus quinquefolia"),
   ("plantain",                  "le plantain",                 "Plantago major"),
   ("trefle-blanc",              "le trèfle blanc",             "Trifolium repens"),
   ("veronique",                 "la véronique",                "Veronica persica"),
   ("capillaire-murailles",      "la capillaire",               "Asplenium trichomanes"),
  ],
 },
 2: {
  "faune": [
   ("cerf-elaphe",           "le cerf",                  "Cervus elaphus"),
   ("chevreuil",             "le chevreuil",             "Capreolus capreolus"),
   ("sanglier",              "le sanglier",              "Sus scrofa"),
   ("renard-roux",           "le renard roux",           "Vulpes vulpes"),
   ("blaireau-europeen",     "le blaireau",              "Meles meles"),
   ("chouette-hulotte",      "la chouette hulotte",      "Strix aluco"),
   ("pic-vert",              "le pic vert",              "Picus viridis"),
   ("salamandre-tachetee",   "la salamandre",            "Salamandra salamandra"),
   ("fourmi-rousse",         "la fourmi rousse",         "Formica rufa"),
   ("lapin-garenne",             "le lapin de garenne",         "Oryctolagus cuniculus"),
   ("martre",                    "la martre",                   "Martes martes"),
   ("loir",                      "le loir",                     "Glis glis"),
   ("geai-des-chenes",           "le geai des chênes",          "Garrulus glandarius"),
   ("pinson-des-arbres",         "le pinson des arbres",        "Fringilla coelebs"),
   ("mulot",                     "le mulot",                    "Apodemus sylvaticus"),
   ("lucane-cerf-volant",        "le lucane cerf-volant",       "Lucanus cervus"),
   ("crapaud-commun",            "le crapaud",                  "Bufo bufo"),
   ("couleuvre-a-collier",       "la couleuvre à collier",      "Natrix natrix"),
  ],
  "flore": [
   ("chene",                 "le chêne",                 "Quercus robur"),
   ("hetre",                 "le hêtre",                 "Fagus sylvatica"),
   ("sapin-blanc",           "le sapin",                 "Abies alba"),
   ("bouleau",               "le bouleau",               "Betula pendula"),
   ("houx",                  "le houx",                  "Ilex aquifolium"),
   ("fougere-aigle",         "la fougère",               "Pteridium aquilinum"),
   ("ronce",                 "la ronce",                 "Rubus fruticosus"),
   ("jacinthe-des-bois",     "la jacinthe des bois",     "Hyacinthoides non-scripta"),
   ("muguet",                "le muguet",                "Convallaria majalis"),
   ("chataignier",               "le châtaignier",              "Castanea sativa"),
   ("charme",                    "le charme",                   "Carpinus betulus"),
   ("frene",                     "le frêne",                    "Fraxinus excelsior"),
   ("noisetier",                 "le noisetier",                "Corylus avellana"),
   ("pin-sylvestre",             "le pin sylvestre",            "Pinus sylvestris"),
   ("if",                        "l’if",                        "Taxus baccata"),
   ("anemone-des-bois",          "l’anémone des bois",          "Anemone nemorosa"),
   ("primevere",                 "la primevère",                "Primula veris"),
   ("digitale",                  "la digitale",                 "Digitalis purpurea"),
  ],
 },
 3: {
  "faune": [
   ("bouquetin-alpes",       "le bouquetin",             "Capra ibex"),
   ("chamois",               "le chamois",               "Rupicapra rupicapra"),
   ("marmotte-alpine",       "la marmotte",              "Marmota marmota"),
   ("aigle-royal",           "l’aigle royal",            "Aquila chrysaetos"),
   ("gypaete-barbu",         "le gypaète barbu",         "Gypaetus barbatus"),
   ("lievre-variable",       "le lièvre variable",       "Lepus timidus"),
   ("hermine",               "l’hermine",                "Mustela erminea"),
   ("lagopede-alpin",        "le lagopède",              "Lagopus muta"),
   ("lynx-boreal",           "le lynx",                  "Lynx lynx"),
   ("chocard",                   "le chocard",                  "Pyrrhocorax graculus"),
   ("tetras-lyre",               "le tétras lyre",              "Lyrurus tetrix"),
   ("cincle-plongeur",           "le cincle plongeur",          "Cinclus cinclus"),
   ("loup-gris",                 "le loup",                     "Canis lupus"),
   ("apollon",                   "l’apollon",                   "Parnassius apollo"),
   ("vautour-fauve",             "le vautour fauve",            "Gyps fulvus"),
   ("vipere-aspic",              "la vipère aspic",             "Vipera aspis"),
   ("triton-alpestre",           "le triton alpestre",          "Ichthyosaura alpestris"),
   ("grand-corbeau",             "le grand corbeau",            "Corvus corax"),
  ],
  "flore": [
   ("epicea",                "l’épicéa",                 "Picea abies"),
   ("meleze",                "le mélèze",                "Larix decidua"),
   ("pin-cembro",            "l’arolle",                 "Pinus cembra"),
   ("rhododendron-ferrugineux", "le rhododendron",       "Rhododendron ferrugineum"),
   ("myrtille",              "la myrtille",              "Vaccinium myrtillus"),
   ("gentiane-acaule",       "la gentiane",              "Gentiana acaulis"),
   ("edelweiss",             "l’edelweiss",              "Leontopodium nivale"),
   ("arnica-montagnes",      "l’arnica",                 "Arnica montana"),
   ("joubarbe",              "la joubarbe",              "Sempervivum montanum"),
   ("pin-a-crochets",            "le pin à crochets",           "Pinus uncinata"),
   ("genevrier",                 "le genévrier",                "Juniperus communis"),
   ("sorbier",                   "le sorbier",                  "Sorbus aucuparia"),
   ("airelle-rouge",             "l’airelle rouge",             "Vaccinium vitis-idaea"),
   ("lis-martagon",              "le lis martagon",             "Lilium martagon"),
   ("campanule",                 "la campanule",                "Campanula scheuchzeri"),
   ("crocus",                    "le crocus",                   "Crocus vernus"),
   ("soldanelle",                "la soldanelle",               "Soldanella alpina"),
   ("silene-acaule",             "le silène acaule",            "Silene acaulis"),
  ],
 },
 4: {
  "faune": [
   ("vache",                 "la vache",                 "Bos taurus"),
   ("mouton",                "le mouton",                "Ovis aries"),
   ("cheval",                "le cheval",                "Equus caballus"),
   ("cochon",                "le cochon",                "Sus scrofa domesticus"),
   ("poule",                 "la poule",                 "Gallus gallus domesticus"),
   ("lievre-europe",         "le lièvre",                "Lepus europaeus"),
   ("cigogne-blanche",       "la cigogne blanche",       "Ciconia ciconia"),
   ("hirondelle-rustique",   "l’hirondelle",             "Hirundo rustica"),
   ("taupe-europe",          "la taupe",                 "Talpa europaea"),
   ("chevre",                    "la chèvre",                   "Capra hircus"),
   ("ane",                       "l’âne",                       "Equus asinus"),
   ("chat",                      "le chat",                     "Felis catus"),
   ("canard-colvert",            "le canard colvert",           "Anas platyrhynchos"),
   ("oie-cendree",               "l’oie",                       "Anser anser"),
   ("buse-variable",             "la buse",                     "Buteo buteo"),
   ("machaon",                   "le machaon",                  "Papilio machaon"),
   ("grenouille-rousse",         "la grenouille",               "Rana temporaria"),
   ("hanneton",                  "le hanneton",                 "Melolontha melolontha"),
  ],
  "flore": [
   ("ble",                   "le blé",                   "Triticum aestivum"),
   ("mais",                  "le maïs",                  "Zea mays"),
   ("tournesol",             "le tournesol",             "Helianthus annuus"),
   ("colza",                 "le colza",                 "Brassica napus"),
   ("pommier",               "le pommier",               "Malus domestica"),
   ("coquelicot",            "le coquelicot",            "Papaver rhoeas"),
   ("bleuet",                "le bleuet",                "Centaurea cyanus"),
   ("trefle-des-pres",       "le trèfle",                "Trifolium pratense"),
   ("ortie",                 "l’ortie",                  "Urtica dioica"),
   ("orge",                      "l’orge",                      "Hordeum vulgare"),
   ("luzerne",                   "la luzerne",                  "Medicago sativa"),
   ("betterave",                 "la betterave",                "Beta vulgaris"),
   ("pomme-de-terre",            "la pomme de terre",           "Solanum tuberosum"),
   ("vigne",                     "la vigne",                    "Vitis vinifera"),
   ("noyer",                     "le noyer",                    "Juglans regia"),
   ("cerisier",                  "le cerisier",                 "Prunus avium"),
   ("marguerite",                "la marguerite",               "Leucanthemum vulgare"),
   ("mauve",                     "la mauve",                    "Malva sylvestris"),
  ],
 },
 5: {
  "faune": [
   ("dauphin-commun",        "le dauphin",               "Delphinus delphis"),
   ("mouette-rieuse",        "la mouette rieuse",        "Chroicocephalus ridibundus"),
   ("goeland-argente",       "le goéland argenté",       "Larus argentatus"),
   ("crabe-vert",            "le crabe",                 "Carcinus maenas"),
   ("etoile-de-mer",         "l’étoile de mer",          "Asterias rubens"),
   ("hippocampe",            "l’hippocampe",             "Hippocampus hippocampus"),
   ("meduse-commune",        "la méduse",                "Aurelia aurita"),
   ("phoque-veau-marin",     "le phoque",                "Phoca vitulina"),
   ("moule-commune",         "la moule",                 "Mytilus edulis"),
   ("bernard-l-ermite",          "le bernard-l’ermite",         "Pagurus bernhardus"),
   ("crevette-rose",             "la crevette",                 "Palaemon serratus"),
   ("oursin",                    "l’oursin",                    "Paracentrotus lividus"),
   ("anemone-de-mer",            "l’anémone de mer",            "Actinia equina"),
   ("patelle",                   "la patelle",                  "Patella vulgata"),
   ("bigorneau",                 "le bigorneau",                "Littorina littorea"),
   ("cormoran",                  "le cormoran",                 "Phalacrocorax carbo"),
   ("huitrier-pie",              "l’huîtrier pie",              "Haematopus ostralegus"),
   ("sterne-pierregarin",        "la sterne",                   "Sterna hirundo"),
  ],
  "flore": [
   ("pin-maritime",          "le pin maritime",          "Pinus pinaster"),
   ("tamaris",               "le tamaris",               "Tamarix gallica"),
   ("oyat",                  "l’oyat",                   "Ammophila arenaria"),
   ("panicaut-maritime",     "le chardon des dunes",     "Eryngium maritimum"),
   ("criste-marine",         "la criste marine",         "Crithmum maritimum"),
   ("salicorne",             "la salicorne",             "Salicornia europaea"),
   ("armerie-maritime",      "l’armérie",                "Armeria maritima"),
   ("fucus",                 "le goémon",                "Fucus vesiculosus"),
   ("laitue-de-mer",         "la laitue de mer",         "Ulva lactuca"),
   ("liseron-des-dunes",         "le liseron des dunes",        "Calystegia soldanella"),
   ("euphorbe-des-dunes",        "l’euphorbe des dunes",        "Euphorbia paralias"),
   ("roquette-de-mer",           "la roquette de mer",          "Cakile maritima"),
   ("obione",                    "l’obione",                    "Halimione portulacoides"),
   ("lavande-de-mer",            "la lavande de mer",           "Limonium vulgare"),
   ("immortelle-des-dunes",      "l’immortelle",                "Helichrysum stoechas"),
   ("laminaire",                 "la laminaire",                "Laminaria digitata"),
   ("dulse",                     "la dulse",                    "Palmaria palmata"),
   ("argousier",                 "l’argousier",                 "Hippophae rhamnoides"),
  ],
 },
}

# Photographies imposées : identifiant d'une photo iNaturalist, quand celle
# retenue automatiquement ne montre pas bien l'espèce. Renseigné après
# relecture des planches contact.
# Les animaux de la ferme n'ont pas d'observation « sauvage » digne de ce nom :
# iNaturalist ne remonte alors que des cochons et des poules retournés à l'état
# féral, impossibles à distinguer d'un sanglier. Ces espèces se cherchent avec
# captive=true, le filtre qui isole justement les animaux d'élevage.
DOMESTIQUES = {
    "Bos taurus", "Ovis aries", "Equus caballus",
    "Sus scrofa domesticus", "Gallus gallus domesticus",
    "Capra hircus", "Equus asinus", "Felis catus", "Anser anser",
}

OVERRIDES = {
    "abeille-domestique": 355572665,
    "aigle-royal": 631265943,
    "armerie-maritime": 497257756,
    "arnica-montagnes": 466384214,
    "blaireau-europeen": 576981233,
    "ble": 113479543,
    "bleuet": 403564813,
    "bouleau": 131880381,
    "bouquetin-alpes": 602532351,
    "cerf-elaphe": 103763755,
    "chamois": 398736721,
    "chene": 216854955,
    "cheval": 99037097,
    "chevreuil": 517308169,
    "chouette-hulotte": 120601572,
    "cigogne-blanche": 601229857,
    "coccinelle-7-points": 186851736,
    "cochon": 220398797,
    "colza": 113010818,
    "coquelicot": 114734674,
    "crabe-vert": 330901450,
    "criste-marine": 405045340,
    "dauphin-commun": 701008453,
    "ecureuil-roux": 357280857,
    "edelweiss": 560454686,
    "epicea": 72268912,
    "etoile-de-mer": 261432691,
    "fougere-aigle": 345054962,
    "fourmi-rousse": 284616165,
    "fucus": 96840209,
    "gentiane-acaule": 22163700,
    "geranium-balcon": 15701482,
    "goeland-argente": 284617710,
    "gypaete-barbu": 364202175,
    "herisson-europe": 79670738,
    "hermine": 489011064,
    "hetre": 274002483,
    "hippocampe": 456289042,
    "hirondelle-rustique": 635249563,
    "houx": 448990835,
    "jacinthe-des-bois": 366527349,
    "joubarbe": 311036488,
    "lagopede-alpin": 20086213,
    "laitue-de-mer": 266271508,
    "lierre": 38428455,
    "lievre-europe": 135144932,
    "lievre-variable": 2887757,
    "lynx-boreal": 246545089,
    "mais": 236433977,
    "marmotte-alpine": 343544695,
    "marronnier": 73427333,
    "martinet-noir": 57115088,
    "meduse-commune": 649274082,
    "meleze": 56039131,
    "merle-noir": 186757278,
    "mesange-charbonniere": 248486851,
    "moineau-domestique": 136543105,
    "mouette-rieuse": 379047525,
    "moule-commune": 155648869,
    "mousse-trottoir": 94133993,
    "mouton": 632127409,
    "muguet": 196688665,
    "myrtille": 670186992,
    "ortie": 26527149,
    "oyat": 208072203,
    "panicaut-maritime": 75688147,
    "paquerette": 601225539,
    "phoque-veau-marin": 331671523,
    "pic-vert": 255640895,
    "pigeon-biset": 367790922,
    "pin-cembro": 207092055,
    "pin-maritime": 605723006,
    "pissenlit": 270994499,
    "platane": 55263068,
    "pommier": 491893168,
    "poule": 467850435,
    "renard-roux": 543807440,
    "rhododendron-ferrugineux": 139065781,
    "ronce": 216279592,
    "rose-tremiere": 272214329,
    "salamandre-tachetee": 186013159,
    "salicorne": 158336699,
    "sanglier": 34825790,
    "sapin-blanc": 661649587,
    "tamaris": 404514988,
    "taupe-europe": 291736892,
    "tilleul": 70594428,
    "tournesol": 155296308,
    "trefle-des-pres": 134044,
    "vache": 51117584,

    "airelle-rouge": 84771646,
    "ane": 199826036,
    "anemone-de-mer": 219461090,
    "anemone-des-bois": 53138673,
    "apollon": 214620544,
    "argousier": 44738853,
    "bernard-l-ermite": 285264344,
    "betterave": 581734004,
    "bigorneau": 478354363,
    "bourdon-terrestre": 707092687,
    "buis": 281668893,
    "buse-variable": 337150135,
    "campanule": 47266022,
    "canard-colvert": 177479326,
    "capillaire-murailles": 679592309,
    "cerisier": 204647799,
    "charme": 271096899,
    "chat": 152222366,
    "chataignier": 236039678,
    "chevre": 470286906,
    "chocard": 111798407,
    "cincle-plongeur": 72611599,
    "cormoran": 484712706,
    "corneille-noire": 28800755,
    "couleuvre-a-collier": 282395845,
    "crapaud-commun": 545983301,
    "crevette-rose": 611509852,
    "crocus": 378878983,
    "digitale": 345544254,
    "dulse": 684401084,
    "epeire-diademe": 323698904,
    "erable-sycomore": 397579449,
    "escargot-petit-gris": 280108055,
    "euphorbe-des-dunes": 37798177,
    "frene": 389562088,
    "geai-des-chenes": 117209356,
    "genevrier": 465009329,
    "grand-corbeau": 613469207,
    "grenouille-rousse": 705912761,
    "hanneton": 193050908,
    "huitrier-pie": 653109895,
    "if": 69192018,
    "immortelle-des-dunes": 366770835,
    "laminaire": 214180984,
    "lapin-garenne": 214613218,
    "lavande-de-mer": 550815768,
    "lezard-murailles": 478187924,
    "lilas": 382335028,
    "lis-martagon": 614274186,
    "liseron-des-dunes": 707128931,
    "loir": 323234441,
    "loup-gris": 246723007,
    "lucane-cerf-volant": 691121128,
    "luzerne": 515036573,
    "machaon": 183409294,
    "marguerite": 11179024,
    "martre": 60067274,
    "mauve": 86794782,
    "mulot": 4818923,
    "noisetier": 77598471,
    "noyer": 80233190,
    "obione": 381949292,
    "oie-cendree": 465540950,
    "orge": 298451337,
    "oursin": 505858992,
    "paon-du-jour": 566316447,
    "patelle": 5313236,
    "pie-bavarde": 461634119,
    "pin-a-crochets": 665991901,
    "pin-sylvestre": 113773630,
    "pinson-des-arbres": 136408520,
    "plantain": 47248877,
    "pomme-de-terre": 135143394,
    "primevere": 29257164,
    "robinier": 225881052,
    "roquette-de-mer": 3495590,
    "rougegorge": 11566966,
    "silene-acaule": 557221619,
    "soldanelle": 367512918,
    "sorbier": 608272149,
    "sterne-pierregarin": 517126849,
    "tetras-lyre": 7137220,
    "tourterelle-turque": 453514613,
    "trefle-blanc": 84331977,
    "triton-alpestre": 474936719,
    "vautour-fauve": 420322179,
    "veronique": 479844481,
    "vigne": 343502942,
    "vigne-vierge": 416689789,
    "vipere-aspic": 405481599,
}


def entrees(periode=None):
    """Itère sur (periode, groupe, slug, nom, taxon)."""
    for p, groupes in sorted(IMAGIER.items()):
        if periode and p != periode:
            continue
        for groupe in ("faune", "flore"):
            for slug, nom, taxon in groupes[groupe]:
                yield p, groupe, slug, nom, taxon
